### ISSUE TITLE
Database Epic

### ISSUE THREAD

**Issue by kelannen** [aaronamk/Roommate-Finder#13]
- [x]  Research #14 
- [x]  Setting up the Database #15 
- [x]  Send/Retrieve Data #16 
- [x]  Create testing data #17
