### ISSUE TITLE
Matching Algorithm Epic

### ISSUE THREAD

**Issue by kelannen** [aaronamk/Roommate-Finder#25]
- [x] Research and Design a Matching Algorithm #26 
- [x] Implement Matching Algorithm #27
- [x] Start Button and Checks #28

Stretch Goal: Improve this algorithm and broaden the amount/type of data in the profile.
