### ISSUE TITLE
Match Result Handling Epic

### ISSUE THREAD

**Issue by kelannen** [aaronamk/Roommate-Finder#29]
- [x] Notification of Match #30 
- [x] Confirmation of Match #31
- [x] Post-Confirmation of Match #32 (stretch goal)
